export const athleteData = {
    profile: {
        name: "Luis Alejandro Valle Barrientos",
        shortName: "Luis Valle",
        origin: "Montenegro, Comuna de Til-Til, Región Metropolitana, Chile",
        discipline: "Trail running, ultra trail, kilómetro vertical, montaña",
        started: 2012,
        phrase: "Desde los cerros de Montenegro a las montañas del mundo.",
        recognitions: [
            "Hijo Ilustre de la Comuna de Til Til 2024/2025",
            "8 veces seleccionado nacional de trail running",
            "Antorcha Parapanamericana 2023 (portador)"
        ]
    },
    links: {
        email: "contacto@luisvalle.cl",
        instagram: "https://www.instagram.com/luisvalleb/",
        facebook: "https://www.facebook.com/profile.php?id=61559929386987",
        youtube: "https://www.youtube.com/@luisvallebarrientos",
        whatsapp: "https://wa.me/qr/XZFAEBVPLJ2RA1",
        utmb: "https://utmb.world/es/runner/487396.luis.vallebarrientos",
        itra: "https://itra.run/api/RunnerSpace/GetRunnerSpace?memberString=XWx7slL7Ce00uMkPH2%2FW1A%3D%3D",
        strava: "https://www.strava.com/athletes/2534523",
        shop: "https://pacul.cl/"
    },
    team: [
        {
            name: "Leonardo Astorga",
            role: "Entrenador desde 2015. Coach Atletismo Nivel 1 IAAF. Especialista fondo y medio fondo. Coordinador Edex Til Til. Jefe técnico Atlético Caleu. Coach Trail Venezuela.",
            link: "https://web.facebook.com/leo.astorga1"
        },
        {
            name: "PACUL",
            role: "Indumentaria deportiva de competición y entrenamiento",
            link: "https://pacul.cl/"
        },
        {
            name: "Francisca Villegas",
            role: "Nutricionista, certificada en nutrición deportiva, vegetariana y deportes de endurance",
            link: "https://www.instagram.com/frantunutri/"
        },
        {
            name: "Dynafit Chile",
            role: "Indumentaria deportiva de competición y entrenamiento",
            link: "https://www.instagram.com/dynafitchile/"
        },
        {
            name: "Municipalidad de Til Til",
            role: "Apoyo institucional",
            link: null
        },
        {
            name: "Eléctrica Til Til",
            role: "Auspiciador",
            link: null
        }
    ],
    videos: [
        "Q1flh29GPWE", "C-ynNEddBa0", "HyGQhBxgddE", "b_Dq5n9c0xM", "sIECUDPdJP4", "Xy9qOdhArmw", "vxQuEBrtcwo", "BTqZizDGWxU", "rxwhTsK4lD8"
    ],
    press: [
        { title: "Entrevista con La Voz del Trail 1", link: "https://www.instagram.com/p/CBb4-b3J6_2/" },
        { title: "Entrevista con La Voz del Trail 2", link: "https://www.instagram.com/p/CBcAVDgpgTv/" },
        { title: "Hijo Ilustre Til Til (video)", link: "https://www.youtube.com/watch?v=sIECUDPdJP4" },
        { title: "Cobertura Runchile — Quito Trail by UTMB", link: "https://runchile.cl/luis-valle-3en-los-50k-del-quito-trail-by-utmb-todos-los-chilenos/" },
        { title: "Cobertura Runchile — Torrencial Valdivia 2024", link: "https://runchile.cl/torrencial-valdivia-2024-fue-una-fiesta-del-trail-running/" },
        { title: "Cobertura Runchile — Putaendo", link: "https://runchile.cl/el-trail-running-lleno-putaendo-de-la-mano-de-latitud-sur-expedition-y-merrell/" }
    ],
    selections: [
        { year: 2017, event: "Sudamericano de Trail", location: "Argentina", flag: "", result: "5° General, 1° por equipos (42K)" },
        { year: 2018, event: "Mundial de Ultra Trail Running", location: "España", flag: "", result: "DNF en km 51 (85K)" },
        { year: 2018, event: "Sudamericano de Trail Running", location: "Uruguay", flag: "", result: "1° General, campeón sudamericano (41K)" },
        { year: 2019, event: "Mundial de Ultra Trail Running", location: "Portugal", flag: "", result: "54° del mundo, 5° sudamericano, 1° chileno" },
        { year: 2019, event: "Mundial de Trail Running", location: "Argentina", flag: "", result: "29° del mundo, 3° sudamericano, 1° chileno" },
        { year: 2020, event: "Sudamericano de Trail Running", location: "Chile", flag: "", result: "Seleccionado (Sin resultado oficial provisto)" },
        { year: 2023, event: "Mundial de Trail Running", location: "Austria", flag: "", result: "Seleccionado (Sin resultado oficial provisto)" },
        { year: 2026, event: "Sudamericano de Trail Running", location: "Samaipata, Bolivia", flag: "", result: "Clasificado" }
    ],
    results: [
        { year: 2012, race: "The North Face Endurance Challenge", distance: "10K", position: "1° General", country: "Chile", highlight: false },
        { year: 2012, race: "Desafío Senderos", distance: "8K", position: "1° General", country: "Chile", highlight: false },
        { year: 2012, race: "X Trail Puchuncaví", distance: "14K", position: "1° General", country: "Chile", highlight: false },
        
        { year: 2013, race: "Trail Running Putaendo", distance: "33K", position: "3° General", country: "Chile", highlight: false },
        { year: 2013, race: "Peñuelas Trail Run", distance: "21K", position: "3°", country: "Chile", highlight: false },
        { year: 2013, race: "Trail Run Valle Aconcagua", distance: "39K", position: "2° General", country: "Chile", highlight: false },
        { year: 2013, race: "Merrell Trekking Tour", distance: "11K", position: "1°", country: "Chile", highlight: false },
        { year: 2013, race: "K42 Altos del Cantillana", distance: "42K", position: "4° General", country: "Chile", highlight: false },
        { year: 2013, race: "X Trail Puchuncaví", distance: "39K", position: "2° General", country: "Chile", highlight: false },
        { year: 2013, race: "Vulcano Ultra Trail", distance: "33K", position: "4° General", country: "Chile", highlight: false },

        { year: 2014, race: "Columbia Trail Challenge", distance: "70K", position: "1° General", country: "Chile", highlight: false },
        { year: 2014, race: "Merrell Trekking Tour", distance: "11K", position: "2° General", country: "Chile", highlight: false },
        { year: 2014, race: "Travesía Til Til–Lampa", distance: "38K", position: "2° General", country: "Chile", highlight: false },
        { year: 2014, race: "K42 Altos del Cantillana", distance: "42K", position: "1° General", country: "Chile", highlight: false },
        { year: 2014, race: "Endurance Challenge", distance: "21K", position: "3° General", country: "Chile", highlight: false },
        { year: 2014, race: "Final K42 Argentina", distance: "42K", position: "11° General", country: "Argentina", highlight: false },

        { year: 2015, race: "Desafío el Sol", distance: "14K", position: "1° General", country: "Chile", highlight: false },
        { year: 2015, race: "Enjoy the Trekking", distance: "21K", position: "3° General", country: "Chile", highlight: false },
        { year: 2015, race: "Desafío Cumbres", distance: "24K", position: "1° General", country: "Chile", highlight: false },
        { year: 2015, race: "Alhué", distance: "35K", position: "2° General", country: "Chile", highlight: false },
        { year: 2015, race: "Putaendo", distance: "100K", position: "1° General", country: "Chile", highlight: false },
        { year: 2015, race: "KV LSE Pirque", distance: "KV", position: "3° General", country: "Chile", highlight: false },
        { year: 2015, race: "Travesía Til Til–Lampa", distance: "38K", position: "1° General", country: "Chile", highlight: false },
        { year: 2015, race: "X Trail Puchuncaví", distance: "50K", position: "4° General", country: "Chile", highlight: false },
        { year: 2015, race: "K42 Altos del Cantillana", distance: "42K", position: "2° General", country: "Chile", highlight: false },
        { year: 2015, race: "Endurance Challenge", distance: "50K", position: "2° General", country: "Chile", highlight: false },
        { year: 2015, race: "Merrell Trekking Tour", distance: "11K", position: "3° General", country: "Chile", highlight: false },

        { year: 2016, race: "Desafío Cumbres", distance: "24K", position: "2° General", country: "Chile", highlight: false },
        { year: 2016, race: "Corrida Vertical Costanera Center", distance: "Vertical", position: "4° General", country: "Chile", highlight: false },
        { year: 2016, race: "Desafío La Cruz, Cabildo", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2016, race: "Alhué", distance: "35K", position: "2° General", country: "Chile", highlight: false },
        { year: 2016, race: "Putaendo", distance: "100K", position: "1° General", country: "Chile", highlight: false },
        { year: 2016, race: "Travesía Til Til–Lampa", distance: "38K", position: "1° General", country: "Chile", highlight: false },
        { year: 2016, race: "Copahue Extremo", distance: "20K", position: "1° General", country: "Argentina", highlight: true },
        { year: 2016, race: "Trail Running El Zaino", distance: "15K", position: "1° General", country: "Chile", highlight: false },
        { year: 2016, race: "KV LSE Canelo", distance: "KV", position: "2° General", country: "Chile", highlight: false },
        { year: 2016, race: "The North Face Endurance Challenge", distance: "80K", position: "2° General", country: "Chile", highlight: false },
        { year: 2016, race: "Adidas Terrex Santiago", distance: "50K", position: "1° General", country: "Chile", highlight: false },
        { year: 2016, race: "Kilómetro Vertical P. Don Toribio", distance: "KV", position: "3° General", country: "Chile", highlight: false },

        { year: 2017, race: "Corrida Florencia Tapia", distance: "6K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Hill Trail Cerro Carbón", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Running Codegua", distance: "-", position: "2° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Mesetas de Jahuel", distance: "12K", position: "2° General", country: "Chile", highlight: false },
        { year: 2017, race: "Corrida Vertical Costanera Center", distance: "62 pisos", position: "1° General", country: "Chile", highlight: true },
        { year: 2017, race: "Trail Running Cabildo", distance: "12K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Running Alhué", distance: "35K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Hill Trail Cerro Pochoco", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Running Putaendo", distance: "30K", position: "3° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Running Doñihue", distance: "20K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Trail Running Olmué", distance: "30K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Travesía Til Til–Lampa", distance: "36K", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Campeonato Nacional Trail Running", distance: "40K", position: "2° General", country: "Chile", highlight: false },
        { year: 2017, race: "Hill Trail Cerro Altos Las Vizcachas", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2017, race: "Campeonato Sudamericano Trail Running", distance: "42K", position: "5° General, 1° por equipos", country: "Argentina", highlight: true },
        { year: 2017, race: "Circuito Hill Trail Chile", distance: "Circuito", position: "Campeón", country: "Chile", highlight: true },

        { year: 2018, race: "Selectivo Mundial Ultra Trail Portugal (Futangue)", distance: "62K", position: "1°", country: "Chile", highlight: false },
        { year: 2018, race: "Climbing Tour Picarquín", distance: "-", position: "2° General Trail", country: "Chile", highlight: false },
        { year: 2018, race: "Desafío La Cruz, Cabildo", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2018, race: "Mundial de Ultra Trail Running", distance: "85K", position: "DNF (km 51)", country: "España", highlight: false },
        { year: 2018, race: "Travesía Til Til–Lampa", distance: "36K", position: "1° General", country: "Chile", highlight: false },
        { year: 2018, race: "Gran Travesía", distance: "100K", position: "1° General", country: "Chile", highlight: false },
        { year: 2018, race: "TNF Endurance Challenge", distance: "21K", position: "2° General", country: "Chile", highlight: false },
        { year: 2018, race: "Altos de Lircay", distance: "30K", position: "1° General", country: "Chile", highlight: false },
        { year: 2018, race: "Campeonato Sudamericano", distance: "41K", position: "1° General", country: "Uruguay", highlight: true },
        { year: 2018, race: "Campeonato Nacional de Ultra Trail (Futangue)", distance: "70K", position: "2° General", country: "Chile", highlight: true },
        { year: 2018, race: "Campeonato Nacional de Trail Running", distance: "-", position: "Campeón Nacional", country: "Chile", highlight: true },

        { year: 2019, race: "Selectivo Mundial Ultra Trail Portugal (Futangue)", distance: "62K", position: "1°", country: "Chile", highlight: false },
        { year: 2019, race: "Santiago 21K", distance: "21K", position: "1h11'50''", country: "Chile", highlight: false },
        { year: 2019, race: "Selectivo Mundial Ultra Trail Portugal (Huilo Huilo)", distance: "44K", position: "1°", country: "Chile", highlight: false },
        { year: 2019, race: "Magma Trail", distance: "28K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Desafío La Cruz, Cabildo", distance: "-", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Climbing Tour Parque Cantillana", distance: "-", position: "1° General Trail", country: "Chile", highlight: false },
        { year: 2019, race: "Trail Running Alhué", distance: "35K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Mundial de Ultra Trail Running", distance: "-", position: "54° del mundo", country: "Portugal", highlight: true },
        { year: 2019, race: "Torrencial Valdivia", distance: "25K", position: "1°", country: "Chile", highlight: false },
        { year: 2019, race: "Campeonato Nacional Huichahue Trail Cunco", distance: "40K", position: "1° General", country: "Chile", highlight: true },
        { year: 2019, race: "Trail Run UC", distance: "21K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Salomon Trail Challenge", distance: "30K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Trail Parque Cordillera", distance: "12K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "TNF Endurance Challenge", distance: "21K", position: "1° General", country: "Chile", highlight: false },
        { year: 2019, race: "Mundial de Trail Running", distance: "-", position: "29° del mundo", country: "Argentina", highlight: true },
        { year: 2019, race: "Vulcano Ultra Trail", distance: "100K", position: "1° General", country: "Chile", highlight: true },

        { year: 2020, race: "Pucón Trail Run", distance: "12K", position: "1° General", country: "Chile", highlight: false },
        { year: 2020, race: "Kilómetro Vertical Alto la Posada", distance: "KV", position: "1° General", country: "Chile", highlight: false },

        { year: 2021, race: "Nahuelbuta Trail", distance: "14K", position: "1° General", country: "Chile", highlight: false },
        { year: 2021, race: "Huilo Huilo Trail Run", distance: "12K", position: "1° General", country: "Chile", highlight: false },
        { year: 2021, race: "Quelembre Trail Cunco", distance: "25K", position: "2° General", country: "Chile", highlight: false },

        { year: 2022, race: "Nahuelbuta Trail", distance: "21K", position: "2° General", country: "Chile", highlight: false },
        { year: 2022, race: "Putaendo Trail", distance: "30K", position: "2° General", country: "Chile", highlight: false },
        { year: 2022, race: "Desafío el Caqui", distance: "14K", position: "2° General", country: "Chile", highlight: false },
        { year: 2022, race: "Andes Mountain Marathon", distance: "21K", position: "1° General", country: "Chile", highlight: false },
        { year: 2022, race: "K42 Series", distance: "42K", position: "1° General", country: "Argentina", highlight: true },
        { year: 2022, race: "Vulcano Ultra Trail", distance: "100K", position: "1° General", country: "Chile", highlight: true },

        { year: 2023, race: "Sprint Vertical Catemu", distance: "-", position: "2° General", country: "Chile", highlight: false },
        { year: 2023, race: "Campeonato Nacional Nahuelbuta", distance: "30K", position: "1° General", country: "Chile", highlight: true },
        { year: 2023, race: "Desafío Quillayquén", distance: "21K", position: "1° General", country: "Chile", highlight: false },
        { year: 2023, race: "Maratón de Temuco", distance: "10K", position: "2° General", country: "Chile", highlight: false },

        { year: 2024, race: "Futangue Challenge", distance: "60K", position: "DNF (km 30)", country: "Chile", highlight: false },
        { year: 2024, race: "Cochrane Patagonia Trail", distance: "35K", position: "2° General", country: "Chile", highlight: false },
        { year: 2024, race: "Valhöll by UTMB", distance: "55K", position: "3° General", country: "Argentina", highlight: true },
        { year: 2024, race: "Monte Verde", distance: "18K", position: "1° General", country: "Chile", highlight: false },
        { year: 2024, race: "Putaendo Trail Run", distance: "33K", position: "1° General", country: "Chile", highlight: false },
        { year: 2024, race: "Torrencial Valdivia", distance: "42K", position: "1° General", country: "Chile", highlight: true },
        { year: 2024, race: "Quito Trail by UTMB", distance: "50K", position: "3° General", country: "Ecuador", highlight: true },
        { year: 2024, race: "Frontera Trail", distance: "30K", position: "2° General", country: "Chile", highlight: false },
        { year: 2024, race: "Trail Running Arica", distance: "22K", position: "1° General", country: "Chile", highlight: false },
        { year: 2024, race: "New Balance", distance: "15K", position: "1° General", country: "Chile", highlight: false },
        { year: 2024, race: "K42 Argentina – Campeonato Sudamericano", distance: "42K", position: "5° General", country: "Argentina", highlight: false },
        { year: 2024, race: "Colico Trail", distance: "22K", position: "1° General", country: "Chile", highlight: false },
        { year: 2024, race: "Andes Mountain Marathon", distance: "42K", position: "1° General", country: "Chile", highlight: false },

        { year: 2025, race: "Campeonato Nacional Desafío Nahuelbuta", distance: "43K", position: "Participación", country: "Chile", highlight: false },
        { year: 2025, race: "Campeonato Nacional Kilómetro Vertical Desafío Quillayquén", distance: "KV", position: "3°", country: "Chile", highlight: false },
        { year: 2025, race: "Desafío Quillayquén", distance: "21K", position: "1° General", country: "Chile", highlight: false },
        { year: 2025, race: "Maratón de Santiago", distance: "21K", position: "1h10'55''", country: "Chile", highlight: false },
        { year: 2025, race: "Santiago Sky Race", distance: "30K", position: "1° General", country: "Chile", highlight: false },
        { year: 2025, race: "Torrencial Valdivia by UTMB", distance: "53K", position: "1° General", country: "Chile", highlight: true },
        { year: 2025, race: "OCC – Ultra Trail du Mont-Blanc", distance: "50K+", position: "43° (5h48)", country: "Francia", highlight: true },
        { year: 2025, race: "Huallerupe Trail", distance: "22K", position: "1° General", country: "Chile", highlight: false },
        { year: 2025, race: "Frontera Trail", distance: "30K", position: "1° General", country: "Chile", highlight: false },
        { year: 2025, race: "K42 Series Villa La Angostura", distance: "42K", position: "1° General", country: "Argentina", highlight: true },
        { year: 2025, race: "Bariloche by UTMB", distance: "22K", position: "2° General", country: "Argentina", highlight: false },
        { year: 2025, race: "El Cruce Saucony", distance: "100K", position: "6° General", country: "Argentina", highlight: false },

        { year: 2026, race: "Kutralkura Trail (Selectiva)", distance: "35K", position: "2° General", country: "Chile", highlight: true },
        { year: 2026, race: "Puesco Trail (Selectiva)", distance: "30K", position: "2° General", country: "Chile", highlight: true },
        { year: 2026, race: "100K Torrencial Chile by UTMB (PILOLCURA)", distance: "106km", position: "1° General", country: "Chile", highlight: true },
        { year: 2026, race: "Dynafit Transalpine Run (7 Etapas)", distance: "258km", position: "1° General", country: "Suiza", highlight: true }
    ],
    torrencialGallery: [
        "PSX_20260630_185747.jpg", "PSX_20260630_185853.jpg", "PSX_20260630_190041.jpg", "PSX_20260630_190301.jpg", 
        "PSX_20260630_190450.jpg", "PSX_20260630_190614.jpg", "PSX_20260630_190841.jpg", "PSX_20260630_191043.jpg",
        "PSX_20260630_191126.jpg", "PSX_20260630_191234.jpg", "PSX_20260630_191333.jpg", "PSX_20260630_191451.jpg",
        "PSX_20260630_191531.jpg", "PSX_20260630_191647.jpg", "PSX_20260630_191823.jpg", "PSX_20260630_193358.jpg",
        "PSX_20260630_195236.jpg", "PSX_20260630_195316.jpg", "ReactNative-snapshot-image332327620208439344.png.jpg", 
        "SaveClip.App_731213489_17955771597173456_3736497041737602941_n.jpg"
    ],
    tarGallery: [
        "TAR 26_S1_Carles Iturbe 2358.jpg",
        "TAR 26_S1_Carles Iturbe_-25.JPG",
        "TAR 26_S2_Carles Iturbe -2173.jpg",
        "TAR 26_S4_Carles Iturbe -3115.jpg",
        "TAR 26_S4_Carles Iturbe -5490.jpg",
        "TAR 26_S5_Carles Iturbe -6528.jpg",
        "TAR 26_S7_Carles Iturbe -0025.jpg",
        "TAR 26_S7_Carles Iturbe -0051.jpg",
        "TAR 26_S7_Carles Iturbe -1250.jpg",
        "TAR 26_S7_Carles Iturbe -9982.jpg",
        "TAR 26_S7_Carles Iturbe -9995.jpg",
        "TAR2026@AndiFrank_07243.jpg",
        "TAR2026@AndiFrank_08942.jpg",
        "TAR2026@AndiFrank_09265.jpg",
        "TAR2026@AndiFrank_10414.jpg",
        "TAR2026@AndiFrank_10420.jpg",
        "TAR2026@AndiFrank_12885.jpg",
        "TAR2026@AndiFrank_12934.jpg",
        "TAR2026@AndiFrank_12953.jpg",
        "TAR2026@AndiFrank_12999.jpg",
        "TAR2026@AndiFrank_14306.jpg",
        "TAR2026@AndiFrank_14308.jpg",
        "TAR2026@AndiFrank_18662.jpg",
        "TAR2026@AndiFrank_18669.jpg",
        "TAR2026@AndiFrank_18679.jpg"
    ]
};
